package group.tonight.healthmanagement.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import group.tonight.healthmanagement.model.HealthDataBean;
import group.tonight.healthmanagement.model.SportDataBean;
import group.tonight.healthmanagement.model.StepDataBean;
import group.tonight.healthmanagement.model.UserBean;

import group.tonight.healthmanagement.dao.HealthDataBeanDao;
import group.tonight.healthmanagement.dao.SportDataBeanDao;
import group.tonight.healthmanagement.dao.StepDataBeanDao;
import group.tonight.healthmanagement.dao.UserBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig healthDataBeanDaoConfig;
    private final DaoConfig sportDataBeanDaoConfig;
    private final DaoConfig stepDataBeanDaoConfig;
    private final DaoConfig userBeanDaoConfig;

    private final HealthDataBeanDao healthDataBeanDao;
    private final SportDataBeanDao sportDataBeanDao;
    private final StepDataBeanDao stepDataBeanDao;
    private final UserBeanDao userBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        healthDataBeanDaoConfig = daoConfigMap.get(HealthDataBeanDao.class).clone();
        healthDataBeanDaoConfig.initIdentityScope(type);

        sportDataBeanDaoConfig = daoConfigMap.get(SportDataBeanDao.class).clone();
        sportDataBeanDaoConfig.initIdentityScope(type);

        stepDataBeanDaoConfig = daoConfigMap.get(StepDataBeanDao.class).clone();
        stepDataBeanDaoConfig.initIdentityScope(type);

        userBeanDaoConfig = daoConfigMap.get(UserBeanDao.class).clone();
        userBeanDaoConfig.initIdentityScope(type);

        healthDataBeanDao = new HealthDataBeanDao(healthDataBeanDaoConfig, this);
        sportDataBeanDao = new SportDataBeanDao(sportDataBeanDaoConfig, this);
        stepDataBeanDao = new StepDataBeanDao(stepDataBeanDaoConfig, this);
        userBeanDao = new UserBeanDao(userBeanDaoConfig, this);

        registerDao(HealthDataBean.class, healthDataBeanDao);
        registerDao(SportDataBean.class, sportDataBeanDao);
        registerDao(StepDataBean.class, stepDataBeanDao);
        registerDao(UserBean.class, userBeanDao);
    }
    
    public void clear() {
        healthDataBeanDaoConfig.clearIdentityScope();
        sportDataBeanDaoConfig.clearIdentityScope();
        stepDataBeanDaoConfig.clearIdentityScope();
        userBeanDaoConfig.clearIdentityScope();
    }

    public HealthDataBeanDao getHealthDataBeanDao() {
        return healthDataBeanDao;
    }

    public SportDataBeanDao getSportDataBeanDao() {
        return sportDataBeanDao;
    }

    public StepDataBeanDao getStepDataBeanDao() {
        return stepDataBeanDao;
    }

    public UserBeanDao getUserBeanDao() {
        return userBeanDao;
    }

}
